#+TITLE: unizar-calendar

[[https://github.com/xzebra/unizar-calendar/actions?query=workflow%3Atests][https://github.com/xzebra/unizar-calendar/workflows/tests/badge.svg]]
[[https://goreportcard.com/badge/github.com/xzebra/unizar-calendar][https://goreportcard.com/report/github.com/xzebra/unizar-calendar]]
[[https://godoc.org/github.com/xzebra/unizar-calendar][https://godoc.org/github.com/xzebra/unizar-calendar?status.svg]]

* Compile
Compilation is automatic thanks to Go modules. That means you have to
enable modules support by setting the environment variable
~GO111MODULE=on~.

#+begin_src sh
go build
#+end_src

* Setup
First of all, go to [[https://developers.google.com/calendar/quickstart/go][Google Calendar API site]], create a new project
with the Calendar API enabled, and save the ~credentials.json~ file in
this project root folder.

After that, compile and run the application. It will ask you to login
and paste the authorization code returned by Google.

Once ~token.json~ and ~credentials.json~ are present in project root
folder, you are good to go.

* Usage
You can interact with the CLI by running the executable from a
terminal. If you want to check the available options, you can use the
flag ~-h~.
#+begin_src sh
$ ./unizar-calendar -h
#+end_src

* Requirements
- Go 1.14 (or higher).
- Go modules enabled.
- Project with Google Calendar API enabled.
- ~credentials.json~ and ~token.json~ generated.
