name: deploy

on:
  schedule:
    - cron: "0 0 * * *" # daily
  workflow_dispatch:
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout config
        uses: actions/checkout@v2
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          
      - name: Build deployer executable
        run: go build -v -o bin ./cmd/webdata
        
      - name: Extract service account data
        run: |
          echo $SERVICE_ACCOUNT > service_account.json
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        
      - name: Run deployer executable and publish results
        run: |
          ./bin/webdata
          mkdir ./publish
          mv -f data.csv ./publish/data.csv
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./service_account.json
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          force_orphan: true
