name: tests

on:
  push:
    branches: [master]
    ignore-paths:
      - 'web/**'
  pull_request:
    branches: [master]
    ignore-paths:
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build for desktop
        run: go build -v ./...

      - name: Build for WebAssembly
        run: go build -v ./...
        env:
          GOOS: js
          GOARCH: wasm

      - name: Test
        run: go test -v ./...
